services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: exploresg-frontend:dev
    container_name: dev-exploresg-frontend-service
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - exploresg-network

# Define the shared network as external
networks:
  exploresg-network:
    name: exploresg-net
    external: true

